// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDul1zgo2vtE72BrDbk9KrVqUemQ23nL3o',
    appId: '1:181765776457:web:80bd10dd887b8c8e534b98',
    messagingSenderId: '181765776457',
    projectId: 'roomify-f1a1c',
    authDomain: 'roomify-f1a1c.firebaseapp.com',
    storageBucket: 'roomify-f1a1c.firebasestorage.app',
    measurementId: 'G-4NDKNS5CB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfajNAINh589IAHp_8T9RdPE0Qy7he_2Y',
    appId: '1:181765776457:android:cd1effdaa282a36f534b98',
    messagingSenderId: '181765776457',
    projectId: 'roomify-f1a1c',
    storageBucket: 'roomify-f1a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIEPMN_2ShG8b2Y6c1710yiTKD77-igCw',
    appId: '1:181765776457:ios:9703bc9f3de5e2b1534b98',
    messagingSenderId: '181765776457',
    projectId: 'roomify-f1a1c',
    storageBucket: 'roomify-f1a1c.firebasestorage.app',
    iosBundleId: 'com.roommate.roomifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIEPMN_2ShG8b2Y6c1710yiTKD77-igCw',
    appId: '1:181765776457:ios:9703bc9f3de5e2b1534b98',
    messagingSenderId: '181765776457',
    projectId: 'roomify-f1a1c',
    storageBucket: 'roomify-f1a1c.firebasestorage.app',
    iosBundleId: 'com.roommate.roomifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDul1zgo2vtE72BrDbk9KrVqUemQ23nL3o',
    appId: '1:181765776457:web:e105fc3c795d7402534b98',
    messagingSenderId: '181765776457',
    projectId: 'roomify-f1a1c',
    authDomain: 'roomify-f1a1c.firebaseapp.com',
    storageBucket: 'roomify-f1a1c.firebasestorage.app',
    measurementId: 'G-HY32K7GBZ2',
  );
}
